#define XLSXIO_VERSION_MAJOR 0
#define XLSXIO_VERSION_MINOR 1
#define XLSXIO_VERSION_MICRO 1

#define VERSION_STRINGIZE_(major, minor, micro) #major"."#minor"."#micro
#define VERSION_STRINGIZE(major, minor, micro) VERSION_STRINGIZE_(major, minor, micro)

#define XLSXIO_VERSION_STRING VERSION_STRINGIZE(XLSXIO_VERSION_MAJOR, XLSXIO_VERSION_MINOR, XLSXIO_VERSION_MICRO)
